return {
    mod_name = {
        en = "Radar",
        fr = "Radar",
        de = "Radar",
        it = "Radar",
        es = "Radar",
        pl = "Radar",
        ["zh-cn"] = "雷达（小地图）",
    },
    mod_description = {
        en = "Displays items, teammates and high-priority enemies on a configurable radar.",
        fr = "Affiche les objets, les équipiers et les ennemis prioritaires sur un radar configurable.",
        de = "Zeigt Gegenstände, Teammitglieder und priorisierte Gegner auf einem konfigurierbaren Radar an.",
        it = "Mostra oggetti, compagni di squadra e nemici ad alta priorità su un radar configurabile.",
        es = "Muestra objetos, compañeros de equipo y enemigos prioritarios en un radar configurable.",
        pl = "Wyświetla przedmioty, członków drużyny i wrogów o wysokim priorytecie na konfigurowalnym radarze.",
        ["zh-cn"] = "在一个可配置的雷达上显示物品、队友和高优先级的敌人。  翻译 by Caimao",
    },

    general_group = {
        en = "General",
        fr = "Général",
        de = "Allgemein",
        it = "Generale",
        es = "General",
        pl = "Ogólne",
        ["zh-cn"] = "常规",
    },
    enable_radar = {
        en = "Enable radar",
        fr = "Activer le radar",
        de = "Radar aktivieren",
        it = "Attiva radar",
        es = "Activar radar",
        pl = "Włącz radar",
        ["zh-cn"] = "启用雷达",
    },
    toggle_radar_key = {
        en = "Toggle radar on or off",
        fr = "Activer ou désactiver le radar",
        de = "Radar ein/aus",
        it = "Attiva o disattiva il radar",
        es = "Activar o desactivar radar",
        pl = "Przełącz radar",
        ["zh-cn"] = "切换雷达开关快捷键",
    },
    radar_size = {
        en = "Radar size",
        fr = "Taille du radar",
        de = "Radargröße",
        it = "Dimensione radar",
        es = "Tamaño del radar",
        pl = "Rozmiar radaru",
        ["zh-cn"] = "雷达尺寸",
    },
    radar_range = {
        en = "Radar range / filter distance (m)",
        fr = "Portée du radar / distance de filtrage (m)",
        de = "Radarreichweite / Filterdistanz (m)",
        it = "Portata radar / distanza filtro (m)",
        es = "Alcance del radar / distancia de filtrado (m)",
        pl = "Zasięg radaru / odległość filtrowania (m)",
        ["zh-cn"] = "雷达范围 / 过滤距离 (米)",
    },
    highlight_distance = {
        en = "Highlight distance",
        fr = "Distance de surbrillance",
        de = "Hervorhebungsdistanz",
        it = "Distanza evidenziazione",
        es = "Distancia de resaltado",
        pl = "Odległość wyróżnienia",
        ["zh-cn"] = "高亮显示距离",
    },
    max_radar_markers = {
        en = "Max radar markers",
        fr = "Nombre max. de marqueurs radar",
        de = "Max. Radarmarkierungen",
        it = "Numero massimo indicatori radar",
        es = "Máx. de marcadores en el radar",
        pl = "Maks. liczba znaczników radaru",
        ["zh-cn"] = "雷达最大标记数量",
    },
    scale_icons_with_radar_size = {
        en = "Scale icons with radar size",
        fr = "Adapter les icônes à la taille du radar",
        de = "Symbole mit Radargröße skalieren",
        it = "Scala le icone in base alla dimensione del radar",
        es = "Escalar iconos con el tamaño del radar",
        pl = "Skaluj ikony wraz z rozmiarem radaru",
        ["zh-cn"] = "图标随雷达尺寸缩放",
    },
    radar_style = {
        en = "Radar style",
        fr = "Style du radar",
        de = "Radarstil",
        it = "Stile radar",
        es = "Estilo del radar",
        pl = "Styl radaru",
        ["zh-cn"] = "雷达样式",
    },
    radar_style_square = {
        en = "Square",
        fr = "Carré",
        de = "Quadrat",
        it = "Quadrato",
        es = "Cuadrado",
        pl = "Kwadrat",
        ["zh-cn"] = "方形",
    },
    radar_style_circle = {
        en = "Circle",
        fr = "Cercle",
        de = "Kreis",
        it = "Cerchio",
        es = "Círculo",
        pl = "Okrąg",
        ["zh-cn"] = "圆形",
    },
    radar_outline = {
        en = "Radar outline",
        fr = "Contour du radar",
        de = "Radarumrandung",
        it = "Contorno radar",
        es = "Contorno del radar",
        pl = "Obrys radaru",
    },
    radar_outline_solid = {
        en = "Solid",
        fr = "Plein",
        de = "Durchgezogen",
        it = "Continuo",
        es = "Sólido",
        pl = "Ciągły",
    },
    radar_outline_dotted = {
        en = "Dotted",
        fr = "Pointillé",
        de = "Gepunktet",
        it = "Punteggiato",
        es = "Punteado",
        pl = "Kropkowany",
    },
    radar_outline_off = {
        en = "Off",
        fr = "Désactivé",
        de = "Aus",
        it = "Disattivato",
        es = "Desactivado",
        pl = "Wyłączone",
    },
    radar_guides = {
        en = "Radar guides",
        fr = "Repères du radar",
        de = "Radarhilfslinien",
        it = "Guide radar",
        es = "Guías del radar",
        pl = "Linie pomocnicze radaru",
    },
    radar_guides_crosshair = {
        en = "Crosshair",
        fr = "Réticule",
        de = "Fadenkreuz",
        it = "Mirino",
        es = "Retícula",
        pl = "Celownik",
    },
    radar_guides_view_guides = {
        en = "View guides",
        fr = "Repères de vue",
        de = "Sichthilfen",
        it = "Guide visuale",
        es = "Guías de vista",
        pl = "Linie widoku",
    },
    radar_guides_range_rings = {
        en = "Range rings",
        fr = "Anneaux de portée",
        de = "Entfernungsringe",
        it = "Anelli di distanza",
        es = "Anillos de alcance",
        pl = "Pierścienie zasięgu",
    },
    radar_guides_off = {
        en = "Off",
        fr = "Désactivé",
        de = "Aus",
        it = "Disattivato",
        es = "Desactivado",
        pl = "Wyłączone",
    },
    enemy_display_style = {
        en = "Enemy marker style",
        fr = "Style des marqueurs d'ennemis",
        de = "Gegnermarkierungsstil",
        it = "Stile indicatori nemici",
        es = "Estilo de marcador de enemigos",
        pl = "Styl znaczników wrogów",
        ["zh-cn"] = "敌人标记样式",
    },
    player_display_style = {
        en = "Player marker style",
        fr = "Style des marqueurs de joueurs",
        de = "Spielermarkierungsstil",
        it = "Stile indicatori giocatori",
        es = "Estilo de marcador de jugadores",
        pl = "Styl znaczników graczy",
        ["zh-cn"] = "玩家标记样式",
    },
    display_style_icon_only = {
        en = "Icon only",
        fr = "Icône seule",
        de = "Nur Symbol",
        it = "Solo icona",
        es = "Solo icono",
        pl = "Tylko ikona",
        ["zh-cn"] = "仅图标",
    },
    display_style_marked_icon = {
        en = "Marked icon",
        fr = "Icône marquée",
        de = "Symbol mit Markierung",
        it = "Icona marcata",
        es = "Icono marcado",
        pl = "Ikona z oznaczeniem",
        ["zh-cn"] = "带标记的图标",
    },
    display_style_dot_only = {
        en = "Dot only",
        fr = "Point seul",
        de = "Nur Punkt",
        it = "Solo punto",
        es = "Solo punto",
        pl = "Tylko kropka",
    },
    display_style_marked_dot = {
        en = "Marked Dot",
        fr = "Point marqué",
        de = "Markierter Punkt",
        it = "Punto marcato",
        es = "Punto marcado",
        pl = "Oznaczona kropka",
    },
    position_group = {
        en = "Position",
        fr = "Position",
        de = "Position",
        it = "Posizione",
        es = "Posición",
        pl = "Pozycja",
        ["zh-cn"] = "位置",
    },
    radar_pos_x = {
        en = "Radar position X",
        fr = "Position X du radar",
        de = "Radarposition X",
        it = "Posizione X radar",
        es = "Posición X del radar",
        pl = "Pozycja radaru X",
        ["zh-cn"] = "雷达位置 X 轴",
    },
    radar_pos_y = {
        en = "Radar position Y",
        fr = "Position Y du radar",
        de = "Radarposition Y",
        it = "Posizione Y radar",
        es = "Posición Y del radar",
        pl = "Pozycja radaru Y",
        ["zh-cn"] = "雷达位置 Y 轴",
    },
    radar_move_step = {
        en = "Steps per input",
        fr = "Pas par entrée",
        de = "Schrittweite pro Eingabe",
        it = "Passi per input",
        es = "Pasos por pulsación",
        pl = "Krok na naciśnięcie",
        ["zh-cn"] = "每次按键的移动步长",
    },
    move_radar_left_key = {
        en = "Move radar left",
        fr = "Déplacer le radar à gauche",
        de = "Radar nach links bewegen",
        it = "Sposta radar a sinistra",
        es = "Mover radar a la izquierda",
        pl = "Przesuń radar w lewo",
        ["zh-cn"] = "快捷键：雷达左移",
    },
    move_radar_right_key = {
        en = "Move radar right",
        fr = "Déplacer le radar à droite",
        de = "Radar nach rechts bewegen",
        it = "Sposta radar a destra",
        es = "Mover radar a la derecha",
        pl = "Przesuń radar w prawo",
        ["zh-cn"] = "快捷键：雷达右移",
    },
    move_radar_up_key = {
        en = "Move radar up",
        fr = "Déplacer le radar vers le haut",
        de = "Radar nach oben bewegen",
        it = "Sposta radar in alto",
        es = "Mover radar hacia arriba",
        pl = "Przesuń radar w górę",
        ["zh-cn"] = "快捷键：雷达上移",
    },
    move_radar_down_key = {
        en = "Move radar down",
        fr = "Déplacer le radar vers le bas",
        de = "Radar nach unten bewegen",
        it = "Sposta radar in basso",
        es = "Mover radar hacia abajo",
        pl = "Przesuń radar w dół",
        ["zh-cn"] = "快捷键：雷达下移",
    },
    common_pickups_group = {
        en = "Common Pickups",
        fr = "Objets ramassables courants",
        de = "Häufige Aufhebobjekte",
        it = "Oggetti comuni",
        es = "Objetos comunes",
        pl = "Popularne przedmioty",
        ["zh-cn"] = "常见拾取物",
    },
    show_crates = {
        en = "Crates",
        fr = "Caisses",
        de = "Kisten",
        it = "Casse",
        es = "Cajas",
        pl = "Skrzynie",
        ["zh-cn"] = "箱子",
    },
    show_ammo_small = {
        en = "Ammo Tin",
        fr = "Boîte de munitions",
        de = "Munitionsdose",
        it = "Scatola di munizioni",
        es = "Caja pequeña de munición",
        pl = "Puszka z amunicją",
        ["zh-cn"] = "弹药罐 (小弹药)",
    },
    show_ammo_big = {
        en = "Ammo Stash",
        fr = "Réserve de munitions",
        de = "Munitionsvorrat",
        it = "Scorta di munizioni",
        es = "Alijo de munición",
        pl = "Zapas amunicji",
        ["zh-cn"] = "弹药储存包 (大弹药)",
    },
    show_grenades = {
        en = "Grenade",
        fr = "Grenade",
        de = "Granate",
        it = "Granata",
        es = "Granada",
        pl = "Granat",
        ["zh-cn"] = "手雷",
    },
    show_pocketable_ammo_crate = {
        en = "Ammo Crate",
        fr = "Caisse de munitions",
        de = "Munitionskiste",
        it = "Cassa di munizioni",
        es = "Caja de munición",
        pl = "Skrzynia z amunicją",
        ["zh-cn"] = "弹药箱",
    },
    show_pocketable_medical_crate = {
        en = "Medical Crate",
        fr = "Caisse médicale",
        de = "Medikiste",
        it = "Cassa medica",
        es = "Caja médica",
        pl = "Skrzynia medyczna",
        ["zh-cn"] = "医疗箱",
    },
    show_pocketable_syringe_ability = {
        en = "Concentration Stimm",
        fr = "Stim de concentration",
        de = "Konzentrations-Stimm",
        it = "Stim di concentrazione",
        es = "Estimulante de concentración",
        pl = "Stym koncentracji",
        ["zh-cn"] = "专注针剂 (黄针)",
    },
    show_pocketable_syringe_corruption = {
        en = "Med Stimm",
        fr = "Médi-stim",
        de = "Med-Stimm",
        it = "Stim medico",
        es = "Estimulante médico",
        pl = "Medi-stym",
        ["zh-cn"] = "医疗针剂 (绿针)",
    },
    show_pocketable_syringe_power = {
        en = "Combat Stimm",
        fr = "Stim de combat",
        de = "Kampf-Stimm",
        it = "Stim da combattimento",
        es = "Estimulante de combate",
        pl = "Stym bojowy",
        ["zh-cn"] = "战斗针剂 (红针)",
    },
    show_pocketable_syringe_speed = {
        en = "Celerity Stimm",
        fr = "Stim de célérité",
        de = "Celerity-Stimm",
        it = "Stim di celerità",
        es = "Estimulante de celeridad",
        pl = "Stym szybkości",
        ["zh-cn"] = "迅捷针剂 (蓝针)",
    },

    materials_group = {
        en = "Collectable Materials",
        fr = "Matériaux à collecter",
        de = "Sammelmaterialien",
        it = "Materiali raccoglibili",
        es = "Materiales coleccionables",
        pl = "Materiały do zebrania",
        ["zh-cn"] = "可收集材料",
    },
    show_diamantine = {
        en = "Diamantine",
        fr = "Diamantine",
        de = "Diamantine",
        it = "Diamantina",
        es = "Diamantina",
        pl = "Diamantyna",
        ["zh-cn"] = "金刚砂",
    },
    show_plasteel = {
        en = "Plasteel",
        fr = "Plastacier",
        de = "Plasteel",
        it = "Plasteel",
        es = "Plastacero",
        pl = "Plasteel",
        ["zh-cn"] = "塑钢",
    },

    primary_objective_group = {
        en = "Primary Objective Items",
        fr = "Objets d'objectif principal",
        de = "Primäre Missionsobjekte",
        it = "Oggetti obiettivo principale",
        es = "Objetos del objetivo principal",
        pl = "Przedmioty celu głównego",
        ["zh-cn"] = "主要目标任务物品",
    },
    show_power_cell_teal = {
        en = "Power Cell",
        fr = "Cellule d'énergie",
        de = "Energiezelle",
        it = "Cella energetica",
        es = "Célula de energía",
        pl = "Ogniwo zasilające",
        ["zh-cn"] = "能量电池",
    },
    show_cryonic_rod = {
        en = "Cryonic Rod",
        fr = "Tige cryonique",
        de = "Kryonikstab",
        it = "Asta criogenica",
        es = "Vara criónica",
        pl = "Pręt kriogeniczny",
        ["zh-cn"] = "冷却棒",
    },
    show_moebian_pox_zetaphyte_13_sample = {
        en = "Moebian Pox Zetaphyte-13 Sample",
        fr = "Échantillon de Pox Zetaphyte-13 de Moebian",
        de = "Moebian Pox Zetaphyte-13-Probe",
        it = "Campione di Peste Zetafita-13 Moebiana",
        es = "Muestra de Moebian Pox Zetaphyte-13",
        pl = "Próbka Moebian Pox Zetaphyte-13",
        ["zh-cn"] = "莫比亚PZ-13样本",
    },
    show_vacuum_capsule = {
        en = "Vacuum Capsule",
        fr = "Capsule sous vide",
        de = "Vakuumkapsel",
        it = "Capsula sottovuoto",
        es = "Cápsula de vacío",
        pl = "Kapsuła próżniowa",
        ["zh-cn"] = "真空舱",
    },
    show_special_issue_ammo = {
        en = "Special Issue Ammo",
        fr = "Munitions spéciales",
        de = "Spezialmunition",
        it = "Munizioni speciali",
        es = "Munición especial",
        pl = "Specjalna amunicja",
        ["zh-cn"] = "特制弹药",
    },
    show_prismata_crystal_repository = {
        en = "Prismata Crystal Repository",
        fr = "Réceptacle de cristal Prismata",
        de = "Prismata-Kristallbehälter",
        it = "Contenitore di cristalli Prismata",
        es = "Contenedor de cristales Prismata",
        pl = "Pojemnik na kryształy Prismata",
        ["zh-cn"] = "棱镜晶体仓库",
    },
    show_mortis_relic = {
        en = "Mortis Relic",
        fr = "Relique Mortis",
        de = "Mortis-Reliquie",
        it = "Reliquia Mortis",
        es = "Reliquia Mortis",
        pl = "Relikt Mortis",
        ["zh-cn"] = "死灵遗物",
    },
    show_coordinates_paper = {
        en = "Coordinates",
        fr = "Coordonnées",
        de = "Koordinaten",
        it = "Coordinate",
        es = "Coordenadas",
        pl = "Koordynaty",
        ["zh-cn"] = "坐标数据",
    },

    secondary_objective_group = {
        en = "Secondary Objective Items",
        fr = "Objets d'objectif secondaire",
        de = "Sekundäre Missionsobjekte",
        it = "Oggetti obiettivo secondario",
        es = "Objetos del objetivo secundario",
        pl = "Przedmioty celu pobocznego",
        ["zh-cn"] = "次要目标任务物品",
    },
    show_pocketable_grimoire = {
        en = "Grimoire",
        fr = "Grimoire",
        de = "Grimoire",
        it = "Grimorio",
        es = "Grimorio",
        pl = "Grimuar",
        ["zh-cn"] = "魔法书",
    },
    show_pocketable_scripture = {
        en = "Scripture",
        fr = "Écriture",
        de = "Schrift",
        it = "Scrittura",
        es = "Escritura",
        pl = "Pismo",
        ["zh-cn"] = "圣经",
    },

    expeditions_specific_group = {
        en = "Expeditions Specific Items",
        fr = "Objets spécifiques aux expéditions",
        de = "Expeditionsspezifische Gegenstände",
        it = "Oggetti specifici delle spedizioni",
        es = "Objetos específicos de expediciones",
        pl = "Przedmioty specyficzne dla ekspedycji",
        ["zh-cn"] = "远征特定物品",
    },
    show_expeditions_currency = {
        en = "Salvage",
        fr = "Récupération",
        de = "Bergungsgut",
        it = "Rottami",
        es = "Chatarra",
        pl = "Złom",
        ["zh-cn"] = "回收物",
    },
    show_expeditions_loot = {
        en = "Tech-Remnants",
        fr = "Vestiges technologiques",
        de = "Technikrelikte",
        it = "Resti tecnologici",
        es = "Restos tecnológicos",
        pl = "Relikty technologii",
        ["zh-cn"] = "科技遗物",
    },
    show_expeditions_dropped_loot = {
        en = "Dropped Tech-Remnants",
        fr = "Vestiges technologiques au sol",
        de = "Fallengelassene Technikrelikte",
        it = "Resti tecnologici a terra",
        es = "Restos tecnológicos caídos",
        pl = "Upuszczone relikty technologii",
        ["zh-cn"] = "掉落科技遗物",
    },
    expeditions_location_group = {
        en = "Expeditions POI",
        fr = "Points d'intérêt des expéditions",
        de = "Expeditions-POIs",
        it = "Punti di interesse spedizioni",
        es = "Puntos de interés de expediciones",
        pl = "Punkty zainteresowania ekspedycji",
    },
    ignore_radar_range_for_expedition_markers = {
        en = "Ignore range limit for POI",
        fr = "Ignorer la limite de portée pour les points d'intérêt",
        de = "Reichweitenlimit für POIs ignorieren",
        it = "Ignora il limite di portata per i punti di interesse",
        es = "Ignorar límite de alcance para puntos de interés",
        pl = "Ignoruj limit zasięgu dla POI",
    },
    show_expedition_objective_opportunity = {
        en = "Sites of Interest",
        fr = "Sites d'intérêt",
        de = "Interessante Orte",
        it = "Siti di interesse",
        es = "Lugares de interés",
        pl = "Miejsca zainteresowania",
    },
    show_expedition_objective_transition = {
        en = "Deadsider Sanctuaries",
        fr = "Sanctuaires Deadsider",
        de = "Deadsider-Sanktuarien",
        it = "Santuari Deadsider",
        es = "Santuarios Deadsider",
        pl = "Sanktuaria Deadsiderów",
    },
    show_expedition_loot_converter = {
        en = "Data Reliquary Harvesters",
        fr = "Moissonneurs de reliquaires de données",
        de = "Datenreliquiar-Ernter",
        it = "Mietitori di reliquiari di dati",
        es = "Recolectores de relicarios de datos",
        pl = "Żniwiarze relikwiarzy danych",
    },
    show_expedition_objective_main_objective = {
        en = "Main Objective",
        fr = "Objectif principal",
        de = "Hauptziel",
        it = "Obiettivo principale",
        es = "Objetivo principal",
        pl = "Cel główny",
    },
    show_expedition_objective_extraction = {
        en = "Valkyrie Extraction Zone",
        fr = "Zone d'extraction Valkyrie",
        de = "Valkyrie-Extraktionszone",
        it = "Zona di estrazione Valkyrie",
        es = "Zona de extracción Valkyrie",
        pl = "Strefa ewakuacji Valkyrii",
    },
    show_expedition_objective_arrival = {
        en = "Valkyrie Arrival Zone",
        fr = "Zone d'arrivée Valkyrie",
        de = "Valkyrie-Landezone",
        it = "Zona di arrivo Valkyrie",
        es = "Zona de llegada Valkyrie",
        pl = "Strefa lądowania Valkyrii",
    },
    show_data_reliquaries = {
        en = "Data Reliquaries",
        fr = "Reliquaires de données",
        de = "Datenreliquiare",
        it = "Reliquiari di dati",
        es = "Relicarios de datos",
        pl = "Relikwiarze danych",
        ["zh-cn"] = "数据圣骨匣",
    },
    show_pocketable_landmine_explosive = {
        en = "Servo-Triggered Mine",
        fr = "Mine à déclenchement servo",
        de = "Servogesteuerte Mine",
        it = "Mina ad attivazione servo",
        es = "Mina activada por servo",
        pl = "Mina aktywowana serwem",
        ["zh-cn"] = "伺服地雷",
    },
    show_pocketable_landmine_fire = {
        en = "Purgation Snare",
        fr = "Piège de purge",
        de = "Läuterungsfalle",
        it = "Trappola purgante",
        es = "Trampa de purga",
        pl = "Sidła oczyszczenia",
        ["zh-cn"] = "涤罪陷阱",
    },
    show_pocketable_landmine_shock = {
        en = "Voltaic Snare",
        fr = "Piège voltaïque",
        de = "Voltaikfalle",
        it = "Trappola voltaica",
        es = "Trampa voltaica",
        pl = "Sidła woltaiczne",
        ["zh-cn"] = "电能陷阱",
    },
    show_pocketable_void_shield = {
        en = "Void Shell",
        fr = "Bouclier du vide",
        de = "Void-Schild",
        it = "Scudo del vuoto",
        es = "Escudo del vacío",
        pl = "Tarcza pustki",
        ["zh-cn"] = "虚空盾",
    },
    show_pocketable_airstrike = {
        en = "Bombing Run Signal Marker",
        fr = "Marqueur de signal pour bombardement",
        de = "Luftangriffs-Signalmarkierer",
        it = "Segnalatore di bombardamento",
        es = "Marcador de señal de bombardeo",
        pl = "Znacznik nalotu bombowego",
        ["zh-cn"] = "空袭信号标记",
    },
    show_pocketable_artillery_strike = {
        en = "Artillery Locator Beacon",
        fr = "Balise de repérage d'artillerie",
        de = "Artillerie-Peilbake",
        it = "Faro di puntamento artiglieria",
        es = "Baliza localizadora de artillería",
        pl = "Radiolatarnia artyleryjska",
        ["zh-cn"] = "炮击定位信标",
    },
    show_pocketable_big_grenade = {
        en = "Modified Grenade",
        fr = "Grenade modifiée",
        de = "Modifizierte Granate",
        it = "Granata modificata",
        es = "Granada modificada",
        pl = "Zmodyfikowany granat",
        ["zh-cn"] = "改装手雷",
    },
    show_pocketable_valkyrie_hover = {
        en = "Fire-Support Signal Marker",
        fr = "Marqueur de signal d'appui-feu",
        de = "Feuerunterstützungs-Signalmarkierer",
        it = "Segnalatore di supporto di fuoco",
        es = "Marcador de señal de apoyo de fuego",
        pl = "Znacznik wsparcia ogniowego",
        ["zh-cn"] = "火力支援信号标记",
    },
    show_promethium_barrel = {
        en = "Promethium Barrel",
        fr = "Baril de prométhéum",
        de = "Promethiumfass",
        it = "Barile di promethium",
        es = "Barril de promethium",
        pl = "Beczka promethium",
        ["zh-cn"] = "钷桶",
    },
    show_large_ammunition_crate = {
        en = "Large Ammunition Crate",
        fr = "Grande caisse de munitions",
        de = "Große Munitionskiste",
        it = "Grande cassa di munizioni",
        es = "Caja grande de munición",
        pl = "Duża skrzynia z amunicją",
        ["zh-cn"] = "大型弹药箱",
    },
    show_anti_rad_stimm = {
        en = "Anti-Rad Stimms",
        fr = "Stims anti-rad",
        de = "Anti-Rad-Stimms",
        it = "Stim anti-rad",
        es = "Estimulantes antirradiación",
        pl = "Stymy antyradiacyjne",
        ["zh-cn"] = "抗辐射兴奋剂",
    },

    martyr_s_skull_group = {
        en = "Martyr's Skull Items",
        fr = "Objets du Crâne du martyr",
        de = "Märtyrerschädel-Gegenstände",
        it = "Oggetti del Teschio del Martire",
        es = "Objetos de la Calavera del Mártir",
        pl = "Przedmioty Czaszki Męczennika",
        ["zh-cn"] = "殉道者头骨物品",
    },
    show_martyr_skull = {
        en = "Martyr's Skull",
        fr = "Crâne du martyr",
        de = "Märtyrerschädel",
        it = "Teschio del Martire",
        es = "Calavera del Mártir",
        pl = "Czaszka Męczennika",
        ["zh-cn"] = "殉道者头骨",
    },
    show_power_cell_orange = {
        en = "Power Cell",
        fr = "Cellule d'énergie",
        de = "Energiezelle",
        it = "Cella energetica",
        es = "Célula de energía",
        pl = "Ogniwo zasilające",
        ["zh-cn"] = "能量电池 (橙色)",
    },

    deployables_group = {
        en = "Deployed Items",
        fr = "Objets déployés",
        de = "Aufgestellte Gegenstände",
        it = "Oggetti schierati",
        es = "Objetos desplegados",
        pl = "Rozstawione przedmioty",
        ["zh-cn"] = "已部署物品",
    },
    show_ammo_crate_deployable = {
        en = "Ammo Crate",
        fr = "Caisse de munitions",
        de = "Munitionskiste",
        it = "Cassa di munizioni",
        es = "Caja de munición",
        pl = "Skrzynia z amunicją",
        ["zh-cn"] = "弹药箱 (已部署)",
    },
    show_medical_crate_deployable = {
        en = "Medical Crate",
        fr = "Caisse médicale",
        de = "Medikiste",
        it = "Cassa medica",
        es = "Caja médica",
        pl = "Skrzynia medyczna",
        ["zh-cn"] = "医疗箱 (已部署)",
    },

    enemies_group = {
        en = "Enemies",
        fr = "Ennemis",
        de = "Gegner",
        it = "Nemici",
        es = "Enemigos",
        pl = "Wrogowie",
        ["zh-cn"] = "敌人",
    },
    show_monstrosities = {
        en = "Monstrosities",
        fr = "Monstruosités",
        de = "Monstrositäten",
        it = "Mostruosità",
        es = "Monstruosidades",
        pl = "Potworności",
        ["zh-cn"] = "怪物",
    },
    show_captains = {
        en = "Captains",
        fr = "Capitaines",
        de = "Kommandanten",
        it = "Capitani",
        es = "Capitanes",
        pl = "Kapitanowie",
        ["zh-cn"] = "连长",
    },
    show_karnak_twins = {
        en = "Karnak Twins",
        fr = "Jumeaux Karnak",
        de = "Karnak-Zwillinge",
        it = "Gemelli Karnak",
        es = "Gemelos Karnak",
        pl = "Bliźnięta Karnak",
        ["zh-cn"] = "双子",
    },

    players_group = {
        en = "Players",
        fr = "Joueurs",
        de = "Spieler",
        it = "Giocatori",
        es = "Jugadores",
        pl = "Gracze",
        ["zh-cn"] = "玩家",
    },
    show_teammates = {
        en = "Teammates",
        fr = "Équipiers",
        de = "Teammitglieder",
        it = "Compagni di squadra",
        es = "Compañeros de equipo",
        pl = "Członkowie drużyny",
        ["zh-cn"] = "队友",
    },

    event_group = {
        en = "Event Related Items",
        fr = "Objets liés aux événements",
        de = "Eventbezogene Gegenstände",
        it = "Oggetti legati agli eventi",
        es = "Objetos relacionados con eventos",
        pl = "Przedmioty związane z wydarzeniami",
        ["zh-cn"] = "事件相关物品",
    },
    show_tainted_skull = {
        en = "Tainted Skulls",
        fr = "Crânes corrompus",
        de = "Verderbte Schädel",
        it = "Teschi corrotti",
        es = "Calaveras corruptas",
        pl = "Skalane czaszki",
        ["zh-cn"] = "受污染的头骨",
    },
    show_pocketable_corrupted_auspex_scanner = {
        en = "Tainted Communications Device",
        fr = "Appareil de communication corrompu",
        de = "Verderbtes Kommunikationsgerät",
        it = "Dispositivo di comunicazione corrotto",
        es = "Dispositivo de comunicaciones corrupto",
        pl = "Skalane urządzenie komunikacyjne",
        ["zh-cn"] = "受污染的通讯设备",
    },
    show_saints = {
        en = "Holy Relics",
        fr = "Saintes reliques",
        de = "Heilige Reliquien",
        it = "Reliquie sacre",
        es = "Reliquias sagradas",
        pl = "Święte relikwie",
        ["zh-cn"] = "圣物",
    },
    show_stolen_rations = {
        en = "Stolen Rations",
        fr = "Rations volées",
        de = "Gestohlene Rationen",
        it = "Razioni rubate",
        es = "Raciones robadas",
        pl = "Skradzione racje",
        ["zh-cn"] = "失窃口粮",
    },

    debug_group = {
        en = "Debugging",
        fr = "Débogage",
        de = "Debug",
        it = "Debug",
        es = "Depuración",
        pl = "Debugowanie",
        ["zh-cn"] = "调试",
    },
    debug_mode = {
        en = "Debug logs",
        fr = "Journaux de débogage",
        de = "Debug-Protokolle",
        it = "Log di debug",
        es = "Registros de depuración",
        pl = "Logi debugowania",
        ["zh-cn"] = "调试日志",
    },
    show_unknown_pickups = {
        en = "Show unknown pickups",
        fr = "Afficher les objets ramassables inconnus",
        de = "Unbekannte Aufhebobjekte anzeigen",
        it = "Mostra oggetti sconosciuti",
        es = "Mostrar objetos desconocidos",
        pl = "Pokaż nieznane przedmioty",
        ["zh-cn"] = "显示未知拾取物",
    },
}