return {
    mod_name = {
        en = "Radar",
        fr = "Radar",
        de = "Radar",
        ["zh-cn"] = "雷达（小地图）",
    },
    mod_description = {
        en = "Displays items, teammates and high-priority enemies on a configurable radar.",
        fr = "Affiche les objets, les équipiers et les ennemis prioritaires sur un radar configurable.",
        de = "Zeigt Gegenstände, Teammitglieder und priorisierte Gegner auf einem konfigurierbaren Radar an.",
        ["zh-cn"] = "在一个可配置的雷达上显示物品、队友和高优先级的敌人。  翻译 by Caimao",
    },

    general_group = {
        en = "General",
        fr = "Général",
        de = "Allgemein",
        ["zh-cn"] = "常规",
    },
    enable_radar = {
        en = "Enable radar",
        fr = "Activer le radar",
        de = "Radar aktivieren",
        ["zh-cn"] = "启用雷达",
    },
    toggle_radar_key = {
        en = "Toggle radar on or off",
        fr = "Activer ou désactiver le radar",
        de = "Radar ein/aus",
        ["zh-cn"] = "切换雷达开关快捷键",
    },
    radar_size = {
        en = "Radar size",
        fr = "Taille du radar",
        de = "Radargröße",
        ["zh-cn"] = "雷达尺寸",
    },
    radar_range = {
        en = "Radar range / filter distance (m)",
        fr = "Portée du radar / distance de filtrage (m)",
        de = "Radarreichweite / Filterdistanz (m)",
        ["zh-cn"] = "雷达范围 / 过滤距离 (米)",
    },
    highlight_distance = {
        en = "Highlight distance",
        fr = "Distance de surbrillance",
        de = "Hervorhebungsdistanz",
        ["zh-cn"] = "高亮显示距离",
    },
    max_radar_markers = {
        en = "Max radar markers",
        fr = "Nombre max. de marqueurs radar",
        de = "Max. Radarmarkierungen",
        ["zh-cn"] = "雷达最大标记数量",
    },
    scale_icons_with_radar_size = {
        en = "Scale icons with radar size",
        fr = "Adapter les icônes à la taille du radar",
        de = "Symbole mit Radargröße skalieren",
        ["zh-cn"] = "图标随雷达尺寸缩放",
    },
    radar_style = {
        en = "Radar style",
        fr = "Style du radar",
        de = "Radarstil",
        ["zh-cn"] = "雷达样式",
    },
    radar_style_square = {
        en = "Square",
        fr = "Carré",
        de = "Quadrat",
        ["zh-cn"] = "方形",
    },
    radar_style_circle = {
        en = "Circle",
        fr = "Cercle",
        de = "Kreis",
        ["zh-cn"] = "圆形",
    },
    radar_outline = {
        en = "Radar outline",
        fr = "Contour du radar",
        de = "Radarumrandung",
    },
    radar_outline_solid = {
        en = "Solid",
        fr = "Plein",
        de = "Durchgezogen",
    },
    radar_outline_dotted = {
        en = "Dotted",
        fr = "Pointillé",
        de = "Gepunktet",
    },
    radar_outline_off = {
        en = "Off",
        fr = "Désactivé",
        de = "Aus",
    },
    radar_guides = {
        en = "Radar guides",
        fr = "Repères du radar",
        de = "Radarhilfslinien",
    },
    radar_guides_crosshair = {
        en = "Crosshair",
        fr = "Réticule",
        de = "Fadenkreuz",
    },
    radar_guides_view_guides = {
        en = "View guides",
        fr = "Repères de vue",
        de = "Sichthilfen",
    },
    radar_guides_range_rings = {
        en = "Range rings",
        fr = "Anneaux de portée",
        de = "Entfernungsringe",
    },
    radar_guides_off = {
        en = "Off",
        fr = "Désactivé",
        de = "Aus",
    },
    enemy_display_style = {
        en = "Enemy marker style",
        fr = "Style des marqueurs d'ennemis",
        de = "Gegnermarkierungsstil",
        ["zh-cn"] = "敌人标记样式",
    },
    player_display_style = {
        en = "Player marker style",
        fr = "Style des marqueurs de joueurs",
        de = "Spielermarkierungsstil",
        ["zh-cn"] = "玩家标记样式",
    },
    display_style_icon_only = {
        en = "Icon only",
        fr = "Icône seule",
        de = "Nur Symbol",
        ["zh-cn"] = "仅图标",
    },
    display_style_marked_icon = {
        en = "Marked icon",
        fr = "Icône marquée",
        de = "Symbol mit Markierung",
        ["zh-cn"] = "带标记的图标",
    },
    display_style_dot_only = {
        en = "Dot only",
        fr = "Point seul",
        de = "Nur Punkt",
    },
    display_style_marked_dot = {
        en = "Marked Dot",
        fr = "Point marqué",
        de = "Markierter Punkt",
    },
    position_group = {
        en = "Position",
        fr = "Position",
        de = "Position",
        ["zh-cn"] = "位置",
    },
    radar_pos_x = {
        en = "Radar position X",
        fr = "Position X du radar",
        de = "Radarposition X",
        ["zh-cn"] = "雷达位置 X 轴",
    },
    radar_pos_y = {
        en = "Radar position Y",
        fr = "Position Y du radar",
        de = "Radarposition Y",
        ["zh-cn"] = "雷达位置 Y 轴",
    },
    radar_move_step = {
        en = "Steps per input",
        fr = "Pas par entrée",
        de = "Schrittweite pro Eingabe",
        ["zh-cn"] = "每次按键的移动步长",
    },
    move_radar_left_key = {
        en = "Move radar left",
        fr = "Déplacer le radar à gauche",
        de = "Radar nach links bewegen",
        ["zh-cn"] = "快捷键：雷达左移",
    },
    move_radar_right_key = {
        en = "Move radar right",
        fr = "Déplacer le radar à droite",
        de = "Radar nach rechts bewegen",
        ["zh-cn"] = "快捷键：雷达右移",
    },
    move_radar_up_key = {
        en = "Move radar up",
        fr = "Déplacer le radar vers le haut",
        de = "Radar nach oben bewegen",
        ["zh-cn"] = "快捷键：雷达上移",
    },
    move_radar_down_key = {
        en = "Move radar down",
        fr = "Déplacer le radar vers le bas",
        de = "Radar nach unten bewegen",
        ["zh-cn"] = "快捷键：雷达下移",
    },
    common_pickups_group = {
        en = "Common Pickups",
        fr = "Objets ramassables courants",
        de = "Häufige Aufhebobjekte",
        ["zh-cn"] = "常见拾取物",
    },
    show_crates = {
        en = "Crates",
        fr = "Caisses",
        de = "Kisten",
        ["zh-cn"] = "箱子",
    },
    show_ammo_small = {
        en = "Ammo Tin",
        fr = "Boîte de munitions",
        de = "Munitionsdose",
        ["zh-cn"] = "弹药罐 (小弹药)",
    },
    show_ammo_big = {
        en = "Ammo Stash",
        fr = "Réserve de munitions",
        de = "Munitionsvorrat",
        ["zh-cn"] = "弹药储存包 (大弹药)",
    },
    show_grenades = {
        en = "Grenade",
        fr = "Grenade",
        de = "Granate",
        ["zh-cn"] = "手雷",
    },
    show_pocketable_ammo_crate = {
        en = "Ammo Crate",
        fr = "Caisse de munitions",
        de = "Munitionskiste",
        ["zh-cn"] = "弹药箱",
    },
    show_pocketable_medical_crate = {
        en = "Medical Crate",
        fr = "Caisse médicale",
        de = "Medikiste",
        ["zh-cn"] = "医疗箱",
    },
    show_pocketable_syringe_ability = {
        en = "Concentration Stimm",
        fr = "Stim de concentration",
        de = "Konzentrations-Stimm",
        ["zh-cn"] = "专注针剂 (黄针)",
    },
    show_pocketable_syringe_corruption = {
        en = "Med Stimm",
        fr = "Médi-stim",
        de = "Med-Stimm",
        ["zh-cn"] = "医疗针剂 (绿针)",
    },
    show_pocketable_syringe_power = {
        en = "Combat Stimm",
        fr = "Stim de combat",
        de = "Kampf-Stimm",
        ["zh-cn"] = "战斗针剂 (红针)",
    },
    show_pocketable_syringe_speed = {
        en = "Celerity Stimm",
        fr = "Stim de célérité",
        de = "Celerity-Stimm",
        ["zh-cn"] = "迅捷针剂 (蓝针)",
    },

    materials_group = {
        en = "Collectable Materials",
        fr = "Matériaux à collecter",
        de = "Sammelmaterialien",
        ["zh-cn"] = "可收集材料",
    },
    show_diamantine = {
        en = "Diamantine",
        fr = "Diamantine",
        de = "Diamantine",
        ["zh-cn"] = "金刚砂",
    },
    show_plasteel = {
        en = "Plasteel",
        fr = "Plastacier",
        de = "Plasteel",
        ["zh-cn"] = "塑钢",
    },

    primary_objective_group = {
        en = "Primary Objective Items",
        fr = "Objets d'objectif principal",
        de = "Primäre Missionsobjekte",
        ["zh-cn"] = "主要目标任务物品",
    },
    show_power_cell_teal = {
        en = "Power Cell",
        fr = "Cellule d'énergie",
        de = "Energiezelle",
        ["zh-cn"] = "能量电池",
    },
    show_cryonic_rod = {
        en = "Cryonic Rod",
        fr = "Tige cryonique",
        de = "Kryonikstab",
        ["zh-cn"] = "冷却棒",
    },
    show_moebian_pox_zetaphyte_13_sample = {
        en = "Moebian Pox Zetaphyte-13 Sample",
        fr = "Échantillon de Pox Zetaphyte-13 de Moebian",
        de = "Moebian Pox Zetaphyte-13-Probe",
        ["zh-cn"] = "莫比亚PZ-13样本",
    },
    show_vacuum_capsule = {
        en = "Vacuum Capsule",
        fr = "Capsule sous vide",
        de = "Vakuumkapsel",
        ["zh-cn"] = "真空舱",
    },
    show_special_issue_ammo = {
        en = "Special Issue Ammo",
        fr = "Munitions spéciales",
        de = "Spezialmunition",
        ["zh-cn"] = "特制弹药",
    },
    show_prismata_crystal_repository = {
        en = "Prismata Crystal Repository",
        fr = "Réceptacle de cristal Prismata",
        de = "Prismata-Kristallbehälter",
        ["zh-cn"] = "棱镜晶体仓库",
    },
    show_mortis_relic = {
        en = "Mortis Relic",
        fr = "Relique Mortis",
        de = "Mortis-Reliquie",
        ["zh-cn"] = "死灵遗物",
    },
    show_coordinates_paper = {
        en = "Coordinates",
        fr = "Coordonnées",
        de = "Koordinaten",
        ["zh-cn"] = "坐标数据",
    },

    secondary_objective_group = {
        en = "Secondary Objective Items",
        fr = "Objets d'objectif secondaire",
        de = "Sekundäre Missionsobjekte",
        ["zh-cn"] = "次要目标任务物品",
    },
    show_pocketable_grimoire = {
        en = "Grimoire",
        fr = "Grimoire",
        de = "Grimoire",
        ["zh-cn"] = "魔法书",
    },
    show_pocketable_scripture = {
        en = "Scripture",
        fr = "Écriture",
        de = "Schrift",
        ["zh-cn"] = "圣经",
    },

    expeditions_specific_group = {
        en = "Expeditions Specific Items",
        fr = "Objets spécifiques aux expéditions",
        de = "Expeditionsspezifische Gegenstände",
        ["zh-cn"] = "远征特定物品",
    },
    show_expeditions_currency = {
        en = "Salvage",
        fr = "Récupération",
        de = "Bergungsgut",
        ["zh-cn"] = "回收物",
    },
    show_expeditions_loot = {
        en = "Tech-Remnants",
        fr = "Vestiges technologiques",
        de = "Technikrelikte",
        ["zh-cn"] = "科技遗物",
    },
    show_expeditions_dropped_loot = {
        en = "Dropped Tech-Remnants",
        fr = "Vestiges technologiques au sol",
        de = "Fallengelassene Technikrelikte",
        ["zh-cn"] = "掉落科技遗物",
    },
    expeditions_location_group = {
        en = "Expeditions POI",
        fr = "Points d'intérêt des expéditions",
        de = "Expeditions-POIs",
    },
    ignore_radar_range_for_expedition_markers = {
        en = "Ignore range limit for POI",
        fr = "Ignorer la limite de portée pour les points d'intérêt",
        de = "Reichweitenlimit für POIs ignorieren",
    },
    show_expedition_objective_opportunity = {
        en = "Sites of Interest",
        fr = "Sites d'intérêt",
        de = "Interessante Orte",
    },
    show_expedition_objective_transition = {
        en = "Deadsider Sanctuaries",
        fr = "Sanctuaires Deadsider",
        de = "Deadsider-Sanktuarien",
    },
    show_expedition_loot_converter = {
        en = "Data Reliquary Harvesters",
        fr = "Moissonneurs de reliquaires de données",
        de = "Datenreliquiar-Ernter",
    },
    show_expedition_objective_main_objective = {
        en = "Main Objective",
        fr = "Objectif principal",
        de = "Hauptziel",
    },
    show_expedition_objective_extraction = {
        en = "Valkyrie Extraction Zone",
        fr = "Zone d'extraction Valkyrie",
        de = "Valkyrie-Extraktionszone",
    },
    show_expedition_objective_arrival = {
        en = "Valkyrie Arrival Zone",
        fr = "Zone d'arrivée Valkyrie",
        de = "Valkyrie-Landezone",
    },
    show_data_reliquaries = {
        en = "Data Reliquaries",
        fr = "Reliquaires de données",
        de = "Datenreliquiare",
        ["zh-cn"] = "数据圣骨匣",
    },
    show_pocketable_landmine_explosive = {
        en = "Servo-Triggered Mine",
        fr = "Mine à déclenchement servo",
        de = "Servogesteuerte Mine",
        ["zh-cn"] = "伺服地雷",
    },
    show_pocketable_landmine_fire = {
        en = "Purgation Snare",
        fr = "Piège de purge",
        de = "Läuterungsfalle",
        ["zh-cn"] = "涤罪陷阱",
    },
    show_pocketable_landmine_shock = {
        en = "Voltaic Snare",
        fr = "Piège voltaïque",
        de = "Voltaikfalle",
        ["zh-cn"] = "电能陷阱",
    },
    show_pocketable_void_shield = {
        en = "Void Shell",
        fr = "Bouclier du vide",
        de = "Void-Schild",
        ["zh-cn"] = "虚空盾",
    },
    show_pocketable_airstrike = {
        en = "Bombing Run Signal Marker",
        fr = "Marqueur de signal pour bombardement",
        de = "Luftangriffs-Signalmarkierer",
        ["zh-cn"] = "空袭信号标记",
    },
    show_pocketable_artillery_strike = {
        en = "Artillery Locator Beacon",
        fr = "Balise de repérage d'artillerie",
        de = "Artillerie-Peilbake",
        ["zh-cn"] = "炮击定位信标",
    },
    show_pocketable_big_grenade = {
        en = "Modified Grenade",
        fr = "Grenade modifiée",
        de = "Modifizierte Granate",
        ["zh-cn"] = "改装手雷",
    },
    show_pocketable_valkyrie_hover = {
        en = "Fire-Support Signal Marker",
        fr = "Marqueur de signal d'appui-feu",
        de = "Feuerunterstützungs-Signalmarkierer",
        ["zh-cn"] = "火力支援信号标记",
    },
    show_promethium_barrel = {
        en = "Promethium Barrel",
        fr = "Baril de prométhéum",
        de = "Promethiumfass",
        ["zh-cn"] = "钷桶",
    },
    show_large_ammunition_crate = {
        en = "Large Ammunition Crate",
        fr = "Grande caisse de munitions",
        de = "Große Munitionskiste",
        ["zh-cn"] = "大型弹药箱",
    },
    show_anti_rad_stimm = {
        en = "Anti-Rad Stimms",
        fr = "Stims anti-rad",
        de = "Anti-Rad-Stimms",
        ["zh-cn"] = "抗辐射兴奋剂",
    },

    martyr_s_skull_group = {
        en = "Martyr's Skull Items",
        fr = "Objets du Crâne du martyr",
        de = "Märtyrerschädel-Gegenstände",
        ["zh-cn"] = "殉道者头骨物品",
    },
    show_martyr_skull = {
        en = "Martyr's Skull",
        fr = "Crâne du martyr",
        de = "Märtyrerschädel",
        ["zh-cn"] = "殉道者头骨",
    },
    show_power_cell_orange = {
        en = "Power Cell",
        fr = "Cellule d'énergie",
        de = "Energiezelle",
        ["zh-cn"] = "能量电池 (橙色)",
    },

    deployables_group = {
        en = "Deployed Items",
        fr = "Objets déployés",
        de = "Aufgestellte Gegenstände",
        ["zh-cn"] = "已部署物品",
    },
    show_ammo_crate_deployable = {
        en = "Ammo Crate",
        fr = "Caisse de munitions",
        de = "Munitionskiste",
        ["zh-cn"] = "弹药箱 (已部署)",
    },
    show_medical_crate_deployable = {
        en = "Medical Crate",
        fr = "Caisse médicale",
        de = "Medikiste",
        ["zh-cn"] = "医疗箱 (已部署)",
    },

    enemies_group = {
        en = "Enemies",
        fr = "Ennemis",
        de = "Gegner",
        ["zh-cn"] = "敌人",
    },
    show_monstrosities = {
        en = "Monstrosities",
        fr = "Monstruosités",
        de = "Monstrositäten",
        ["zh-cn"] = "怪物",
    },
    show_captains = {
        en = "Captains",
        fr = "Capitaines",
        de = "Kommandanten",
        ["zh-cn"] = "连长",
    },
    show_karnak_twins = {
        en = "Karnak Twins",
        fr = "Jumeaux Karnak",
        de = "Karnak-Zwillinge",
        ["zh-cn"] = "双子",
    },

    players_group = {
        en = "Players",
        fr = "Joueurs",
        de = "Spieler",
        ["zh-cn"] = "玩家",
    },
    show_teammates = {
        en = "Teammates",
        fr = "Équipiers",
        de = "Teammitglieder",
        ["zh-cn"] = "队友",
    },

    event_group = {
        en = "Event Related Items",
        fr = "Objets liés aux événements",
        de = "Eventbezogene Gegenstände",
        ["zh-cn"] = "事件相关物品",
    },
    show_tainted_skull = {
        en = "Tainted Skulls",
        fr = "Crânes corrompus",
        de = "Verderbte Schädel",
        ["zh-cn"] = "受污染的头骨",
    },
    show_pocketable_corrupted_auspex_scanner = {
        en = "Tainted Communications Device",
        fr = "Appareil de communication corrompu",
        de = "Verderbtes Kommunikationsgerät",
        ["zh-cn"] = "受污染的通讯设备",
    },
    show_saints = {
        en = "Holy Relics",
        fr = "Saintes reliques",
        de = "Heilige Reliquien",
        ["zh-cn"] = "圣物",
    },
    show_stolen_rations = {
        en = "Stolen Rations",
        fr = "Rations volées",
        de = "Gestohlene Rationen",
        ["zh-cn"] = "失窃口粮",
    },

    debug_group = {
        en = "Debugging",
        fr = "Débogage",
        de = "Debug",
        ["zh-cn"] = "调试",
    },
    debug_mode = {
        en = "Debug logs",
        fr = "Journaux de débogage",
        de = "Debug-Protokolle",
        ["zh-cn"] = "调试日志",
    },
    show_unknown_pickups = {
        en = "Show unknown pickups",
        fr = "Afficher les objets ramassables inconnus",
        de = "Unbekannte Aufhebobjekte anzeigen",
        ["zh-cn"] = "显示未知拾取物",
    },
}